CREATE TABLE IF NOT EXISTS stats.commands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  logged_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  guildFlake TEXT NOT NULL,
  command TEXT NOT NULL,
  locale TEXT
);

CREATE TABLE IF NOT EXISTS stats.timing (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event TEXT NOT NULL,
  serialized TEXT,
  context TEXT,
  began REAL NOT NULL,
  finished REAL NOT NULL,
  duration REAL GENERATED ALWAYS AS (finished-began) STORED,
  logged_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
