name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:

    runs-on: ubuntu-latest
    container: node:current

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - run: npm ci
    - run: npm run test:ci
